Remember install and uninstall options via global config file

diff --git a/dist/manage b/dist/manage
--- a/dist/manage
+++ b/dist/manage
@@ -2,11 +2,133 @@
 
 set -euo pipefail
 
-#== UTILITIES ==================================================================
+#== GLOBALS ====================================================================
 
 absolute-path-of() {
   echo $(cd "$(dirname "$1")" &>/dev/null && pwd)/$(basename "$1")
 }
+
+PROJECT_DIR=$(dirname $(dirname $(absolute-path-of $0)))
+SOURCE_DIR="$PROJECT_DIR/src"
+COMMAND=
+DOTFILES_HOME=${DOTFILES_HOME:-$HOME}
+CONFIG_FILE_PATH="$DOTFILES_HOME/.dotfilesrc"
+declare -A COMMON_CONFIG
+COMMON_CONFIG=([dry_run]=0 [force]=0 [verbose]=0)
+declare -A INSTALL_CONFIG
+
+#== CONFIG =====================================================================
+
+config::read() {
+  # Inspiration: <https://forums.bunsenlabs.org/viewtopic.php?id=5570>
+
+  local file="$1"
+  shift
+
+  local arg
+  local -A config_variable_map
+
+  while [[ ${1:-} ]]; do
+    arg="${1:-}"
+    case "$arg" in
+      --*)
+        config_variable_map[${arg#--}]="$2"
+        shift 2
+        ;;
+      *)
+        error "Unknown argument '$arg' given."
+        exit 1
+    esac
+  done
+
+  local -n current_config_array
+  local section_regex="^\[([[:alpha:]_][[:alnum:]_]*)\]$"
+  local entry_regex="^([^=]+)=(.+)$"
+  local lines line key value
+
+  while read -r line; do
+    if [[ -n $line ]]; then
+      if [[ $line =~ $section_regex ]]; then
+        if [[ -n ${BASH_REMATCH[1]} ]]; then
+          local -n current_config_array=${config_variable_map[${BASH_REMATCH[1]}]}
+        else
+          echo "section_regex match failed"
+          exit 1
+        fi
+      elif [[ $line =~ $entry_regex ]]; then
+        if [[ -n ${BASH_REMATCH[1]} && -n ${BASH_REMATCH[2]} ]]; then
+          key=$(config::clean-key ${BASH_REMATCH[1]})
+          value=$(config::clean-value ${BASH_REMATCH[2]})
+          current_config_array["${key}"]="${value}"
+        else
+          echo "entry_regex match failed"
+          exit 1
+        fi
+      else
+        echo "Could not parse line: $line"
+        exit 1
+      fi
+    fi
+  done < "$file"
+
+  declare -p COMMON_CONFIG
+  declare -p INSTALL_CONFIG
+}
+
+config::write() {
+  local file="$1"
+  shift
+
+  local arg
+  local -A config_variable_map=()
+
+  while [[ ${1:-} ]]; do
+    arg="${1:-}"
+    case "$arg" in
+      --*)
+        config_variable_map[${arg#--}]="$2"
+        shift 2
+        ;;
+      *)
+        error "Unknown argument '$arg' given."
+        exit 1
+    esac
+  done
+
+  rm -f $file
+
+  local index=0
+  for section_name in "${!config_variable_map[@]}"; do
+    local -n config_array=${config_variable_map[$section_name]}
+    if [[ $index -gt 0 ]]; then
+      echo >> $file
+    fi
+    echo "[$section_name]" >> $file
+
+    for key in "${!config_array[@]}"; do
+      if [[ "${config_array[$key]}" =~ ^[[:digit:]]+$ ]]; then
+        echo "$key = ${config_array[$key]}" >> $file
+      else
+        echo "$key = \"${config_array[$key]}\"" >> $file
+      fi
+    done
+
+    index=$index+1
+  done
+}
+
+config::clean-key() {
+  echo "$1" | sed -Ee 's/^[[:blank:]]+|[[:blank:]]+$//'
+}
+
+config::clean-value() {
+  echo "$1" | \
+    sed -Ee 's/^[[:blank:]]+|[[:blank:]]+$//' | \
+    sed -Ee "s/\"(.+)\"/\\1/" |
+    sed -Ee "s/'(.+)'/\\1/"
+}
+
+#== UTILITIES ==================================================================
 
 colorize() {
   local code=
@@ -74,11 +196,6 @@ files-equal() {
 }
 
 #== COMMON =====================================================================
-
-PROJECT_DIR=$(dirname $(dirname $(absolute-path-of $0)))
-SOURCE_DIR="$PROJECT_DIR/src"
-COMMAND=
-DOTFILES_HOME=${DOTFILES_HOME:-$HOME}
 
 inspect-command() {
   echo "                 >" "$@"
@@ -182,6 +299,24 @@ announce() {
 
 #== INSTALL ====================================================================
 
+install__parse-args() {
+  local arg
+
+  while [[ ${1:-} ]]; do
+    arg="${1:-}"
+    case "$arg" in
+      --*)
+        INSTALL_CONFIG["${arg#--}"]="$2"
+        shift 2
+        ;;
+      *)
+        error "Unknown argument '$arg' given."
+        echo "Please run $0 install --help for usage."
+        exit 1
+    esac
+  done
+}
+
 install__print-help() {
   cat <<TEXT
 $(colorize blue "## DESCRIPTION")
@@ -242,48 +377,6 @@ and OTHER_OPTIONS are one or more of:
 --help, -h
   You're looking at it ;)
 TEXT
-}
-
-install__parse-args() {
-  DRY_RUN=0
-  FORCE=0
-  VERBOSE=0
-
-  local arg=
-
-  while [[ ${1:-} ]]; do
-    arg="${1:-}"
-    case "$arg" in
-      --git-email)
-        GIT_EMAIL="$2"
-        shift 2
-        ;;
-      --git-name)
-        GIT_NAME="$2"
-        shift 2
-        ;;
-      --dry-run | --noop | -n)
-        DRY_RUN=1
-        shift
-        ;;
-      --force | -f)
-        FORCE=1
-        shift
-        ;;
-      --verbose | -V)
-        VERBOSE=1
-        shift
-        ;;
-      --help | -h | -?)
-        ${COMMAND}__print-help | more -R
-        exit
-        ;;
-      *)
-        error "Unknown argument '$arg' given."
-        echo "Please run $0 $COMMAND --help for usage."
-        exit 1
-    esac
-  done
 }
 
 install__determine-action-color() {
@@ -350,56 +443,24 @@ install__announce() {
 }
 
 install__read-config-file() {
-  # Inspiration: <https://forums.bunsenlabs.org/viewtopic.php?id=5570>
+  local -A symlinks
+  config::read "$1" --symlinks symlinks
 
-  local full_path="$1"
-  local section_regex="^\[([[:alpha:]_][[:alnum:]_]*)\]$"
-  local entry_regex="^([^=]+)=(.+)$"
-  local line key value
-  declare -Ag CONFIG_SYMLINKS
-
-  while read -r line; do
-    if [[ -n $line ]]; then
-      if [[ $line =~ $section_regex ]]; then
-        if [[ -n ${BASH_REMATCH[1]} ]]; then
-          local -n current_config_array="CONFIG_$(echo ${BASH_REMATCH[1]} | tr '[:lower:]' '[:upper:]')"
-        else
-          echo "section_regex match failed"
-          exit 1
-        fi
-      elif [[ $line =~ $entry_regex ]]; then
-        if [[ -z ${!current_config_array} ]]; then
-          echo "no section defined yet!"
-          exit 1
-        fi
-
-        if [[ -n ${BASH_REMATCH[1]} && -n ${BASH_REMATCH[2]} ]]; then
-          key=$(echo ${BASH_REMATCH[1]} | sed -e 's/^[[:blank:]]+|[[:blank:]]+$//')
-          value=$(echo ${BASH_REMATCH[2]} | sed -e 's/^[[:blank:]]+|[[:blank:]]+$//')
-          current_config_array["${key}"]="${value}"
-        else
-          echo "entry_regex match failed"
-          exit 1
-        fi
-      fi
-    fi
-  done < "$full_path"
-
-  for source_path in ${!CONFIG_SYMLINKS[@]}; do
+  for source_path in ${!symlinks[@]}; do
     install__link-file-with-announcement \
       "$(absolute-path-of "$dir/$source_path")" \
-      "${CONFIG_SYMLINKS[$source_path]}"
+      "${symlinks[$source_path]}"
   done
 }
 
 install__run-install-script() {
   local full_path="$1"
 
-  if [[ $VERBOSE -eq 1 ]]; then
+  if [[ ${COMMON_CONFIG[verbose]} -eq 1 ]]; then
     eval inspect-command env ${GIT_NAME:+'GIT_NAME="$GIT_NAME"'} ${GIT_EMAIL:+'GIT_EMAIL="$GIT_EMAIL"'} '"$full_path"'
   fi
 
-  if [[ $DRY_RUN -eq 0 ]]; then
+  if [[ ${COMMON_CONFIG[dry_run]} -eq 0 ]]; then
     set +e
 
     eval env ${GIT_NAME:+'GIT_NAME="$GIT_NAME"'} ${GIT_EMAIL:+'GIT_EMAIL="$GIT_EMAIL"'} '"$full_path"'
@@ -420,20 +481,20 @@ install__copy-file() {
   local full_source_path="$1"
   local full_destination_path="$2"
 
-  if [[ $VERBOSE -eq 1 ]]; then
+  if [[ ${COMMON_CONFIG[verbose]} -eq 1 ]]; then
     inspect-command mkdir -p $(dirname "$full_destination_path")
 
-    if [[ $FORCE -eq 1 ]]; then
+    if [[ ${COMMON_CONFIG[force]} -eq 1 ]]; then
       inspect-command rm -f "$full_destination_path"
     fi
 
     inspect-command cp "$full_source_path" "$full_destination_path"
   fi
 
-  if [[ $DRY_RUN -eq 0 ]]; then
+  if [[ ${COMMON_CONFIG[dry_run]} -eq 0 ]]; then
     mkdir -p $(dirname "$full_destination_path")
 
-    if [[ $FORCE -eq 1 ]]; then
+    if [[ ${COMMON_CONFIG[force]} -eq 1 ]]; then
       rm -f "$full_destination_path"
     fi
 
@@ -448,7 +509,7 @@ install__process-non-link() {
   local full_destination_path=$(build-destination-path "$destination_path")
 
   if [[ -e $full_destination_path ]]; then
-    if [[ $FORCE -eq 1 ]]; then
+    if [[ ${COMMON_CONFIG[force]} -eq 1 ]]; then
       announce non-link overwrite -s "$full_source_path" -d "$full_destination_path"
       install__copy-file "$full_source_path" "$full_destination_path"
     else
@@ -464,20 +525,20 @@ install__link-file() {
   local full_source_path="$1"
   local full_destination_path="$2"
 
-  if [[ $VERBOSE -eq 1 ]]; then
+  if [[ ${COMMON_CONFIG[verbose]} -eq 1 ]]; then
     inspect-command mkdir -p $(dirname "$full_destination_path")
 
-    if [[ $FORCE -eq 1 ]]; then
+    if [[ ${COMMON_CONFIG[force]} -eq 1 ]]; then
       inspect-command rm -rf "$full_destination_path"
     fi
 
     inspect-command ln -s "$full_source_path" "$full_destination_path"
   fi
 
-  if [[ $DRY_RUN -eq 0 ]]; then
+  if [[ ${COMMON_CONFIG[dry_run]} -eq 0 ]]; then
     mkdir -p $(dirname "$full_destination_path")
 
-    if [[ $FORCE -eq 1 ]]; then
+    if [[ ${COMMON_CONFIG[force]} -eq 1 ]]; then
       rm -rf "$full_destination_path"
     fi
 
@@ -507,7 +568,7 @@ install__link-file-with-announcement() {
   local full_destination_path="$2"
 
   if [[ -e $full_destination_path ]]; then
-    if [[ $FORCE -eq 1 ]]; then
+    if [[ ${COMMON_CONFIG[force]} -eq 1 ]]; then
       announce link overwrite -s "$full_source_path" -d "$full_destination_path"
       install__link-file "$full_source_path" "$full_destination_path"
     else
@@ -520,7 +581,7 @@ install__link-file-with-announcement() {
 }
 
 install__print-result() {
-  if [[ $DRY_RUN -eq 1 ]]; then
+  if [[ ${COMMON_CONFIG[dry_run]} -eq 1 ]]; then
     echo
     info "Don't worry — no files were created!"
   else
@@ -531,6 +592,20 @@ install__print-result() {
 }
 
 #== UNINSTALL ==================================================================
+
+uninstall__parse-args() {
+  local arg=
+
+  while [[ ${1:-} ]]; do
+    arg="${1:-}"
+    case "$arg" in
+      *)
+        error "Unknown argument '$arg' given."
+        echo "Please run $0 $COMMAND --help for usage."
+        exit 1
+    esac
+  done
+}
 
 uninstall__print-help() {
   cat <<TEXT
@@ -587,46 +662,6 @@ where OPTIONS are:
 --help, -h
   You're looking at it ;)
 TEXT
-}
-
-uninstall__parse-args() {
-  DRY_RUN=0
-  FORCE=0
-  VERBOSE=0
-
-  local arg=
-
-  if [[ $# -eq 0 ]]; then
-    error "No arguments given."
-    echo "Please run $0 $COMMAND --help for usage."
-    exit 1
-  fi
-
-  while [[ ${1:-} ]]; do
-    arg="${1:-}"
-    case "$arg" in
-      --dry-run | --noop | -n)
-        DRY_RUN=1
-        shift
-        ;;
-      --force | -f)
-        FORCE=1
-        shift
-        ;;
-      --verbose | -V)
-        VERBOSE=1
-        shift
-        ;;
-      --help | -h | -?)
-        ${COMMAND}__print-help | more -R
-        exit
-        ;;
-      *)
-        error "Unknown argument '$arg' given."
-        echo "Please run $0 $COMMAND --help for usage."
-        exit 1
-    esac
-  done
 }
 
 uninstall__determine-action-color() {
@@ -688,11 +723,11 @@ uninstall__announce() {
 uninstall__remove-file() {
   local full_destination_path="$1"
 
-  if [[ $VERBOSE -eq 1 ]]; then
+  if [[ ${COMMON_CONFIG[verbose]} -eq 1 ]]; then
     inspect-command rm "$full_destination_path"
   fi
 
-  if [[ $DRY_RUN -eq 0 ]]; then
+  if [[ ${COMMON_CONFIG[dry_run]} -eq 0 ]]; then
     rm "$full_destination_path"
   fi
 }
@@ -704,7 +739,7 @@ uninstall__process-non-link() {
   local full_destination_path=$(build-destination-path "$destination_path")
 
   if [[ -f $full_destination_path ]]; then
-    if files-equal "$full_source_path" "$full_destination_path" || [[ $FORCE -eq 1 ]]; then
+    if files-equal "$full_source_path" "$full_destination_path" || [[ ${COMMON_CONFIG[force]} -eq 1 ]]; then
       announce non-link delete -s "$full_source_path" -d "$full_destination_path"
       uninstall__remove-file "$full_destination_path"
     else
@@ -724,7 +759,7 @@ uninstall__process-entry() {
     announce link delete -s "$full_source_path" -d "$full_destination_path"
     uninstall__remove-file "$full_destination_path"
   elif [[ -e $full_destination_path ]]; then
-    if [[ $FORCE -eq 1 ]]; then
+    if [[ ${COMMON_CONFIG[force]} -eq 1 ]]; then
       announce entry purge -s "$full_source_path"
       uninstall__remove-file "$full_destination_path"
     else
@@ -734,7 +769,7 @@ uninstall__process-entry() {
 }
 
 uninstall__print-result() {
-  if [[ $DRY_RUN -eq 1 ]]; then
+  if [[ ${COMMON_CONFIG[dry_run]} -eq 1 ]]; then
     echo
     info "Don't worry — no files were removed!"
   else
@@ -745,6 +780,16 @@ uninstall__print-result() {
 }
 
 #== MAIN ======================================================================
+
+read-config-file() {
+  if [[ -f $CONFIG_FILE_PATH ]]; then
+    config::read $CONFIG_FILE_PATH --install INSTALL_CONFIG
+  fi
+}
+
+write-config-file() {
+  config::write $CONFIG_FILE_PATH --install INSTALL_CONFIG
+}
 
 print-help() {
   cat <<TEXT
@@ -768,6 +813,8 @@ TEXT
 }
 
 parse-args() {
+  local rest
+
   if [[ $# -eq 0 ]]; then
     error "Missing command."
     echo "Please run $0 --help for usage."
@@ -781,7 +828,7 @@ parse-args() {
       ;;
     install | uninstall)
       COMMAND="$1"
-      ${COMMAND}__parse-args "${@:2}"
+      shift
       ;;
     *)
       error "Unknown command '$arg'."
@@ -789,6 +836,35 @@ parse-args() {
       exit 1
       ;;
   esac
+
+  rest=()
+  while [[ ${1:-} ]]; do
+    arg="${1:-}"
+    case "$arg" in
+      --dry-run | --noop | -n)
+        COMMON_CONFIG[dry_run]=1
+        shift
+        ;;
+      --force | -f)
+        COMMON_CONFIG[force]=1
+        shift
+        ;;
+      --verbose | -V)
+        COMMON_CONFIG[verbose]=1
+        shift
+        ;;
+      --help | -h | -?)
+        ${COMMAND}__print-help | more -R
+        exit
+        ;;
+      *)
+        rest+=("$arg")
+        shift
+        ;;
+    esac
+  done
+
+  ${COMMAND}__parse-args "${rest[@]}"
 }
 
 process-entry() {
@@ -835,11 +911,16 @@ recurse-dir() {
 }
 
 main() {
+  read-config-file
   parse-args "$@"
+
+  if [[ ${COMMON_CONFIG[dry_run]} -eq 0 ]]; then
+    write-config-file
+  fi
 
   case $COMMAND in
     install | uninstall)
-      if [[ $DRY_RUN -eq 1 ]]; then
+      if [[ ${COMMON_CONFIG[dry_run]} -eq 1 ]]; then
         info "Running in dry-run mode."
         echo
       fi
