Add a way to specify additional symlinks via a config file
If you add a file called __overrides__.cfg to the root source directory,
then you can specify symlinks that should be created that are outside of
the home directory.

Also update:

* ._no-link -> .__no-link__
* ._install.sh -> .__install__.sh

diff --git a/dist/manage b/dist/manage
--- a/dist/manage
+++ b/dist/manage
@@ -76,6 +76,7 @@ files-equal() {
 #== COMMON =====================================================================
 
 PROJECT_DIR=$(dirname $(dirname $(absolute-path-of $0)))
+SOURCE_DIR="$PROJECT_DIR/src"
 COMMAND=
 DOTFILES_HOME=${DOTFILES_HOME:-$HOME}
 
@@ -158,7 +159,7 @@ announce() {
   local color=
   color="$(${COMMAND}__determine-action-color "$action")"
   if [[ $? -eq 1 ]]; then
-    error "Invalid color '$action'!"
+    error "Couldn't find color for action '$action'!"
     echo "Please check the definition of ${COMMAND}__determine-action-color()."
     exit 1
   fi
@@ -203,9 +204,9 @@ There are some exceptions to this:
 * If it encounters a file anywhere called _install.sh, it will treat that file
   as an executable and run it. (It assumes you have chmod'd this file correctly
   and that this script has a shebang.)
-* If it encounters a file anywhere that ends in ._no-link, it will copy this
+* If it encounters a file anywhere that ends in .__no-link__, it will copy this
   file to your home directory instead of creating a symlink.
-  EXAMPLE: src/gitconfig._no-link creates a file (not a symlink) at
+  EXAMPLE: src/gitconfig.__no-link__ creates a file (not a symlink) at
   ~/.gitconfig.
 * If it encounters a directory anywhere that has a .no-recurse file, it will
   NOT recurse the directory; instead, it will create a symlink for the
@@ -289,7 +290,7 @@ install__determine-action-color() {
   local action="$1"
 
   case $action in
-    create | run)
+    create | run | read)
       echo "green"
       ;;
     overwrite)
@@ -348,22 +349,65 @@ install__announce() {
   fi
 }
 
+install__read-config-file() {
+  # Inspiration: <https://forums.bunsenlabs.org/viewtopic.php?id=5570>
+
+  local full_path="$1"
+  local section_regex="^\[([[:alpha:]_][[:alnum:]_]*)\]$"
+  local entry_regex="^([^=]+)=(.+)$"
+  local line key value
+  declare -Ag CONFIG_SYMLINKS
+
+  while read -r line; do
+    if [[ -n $line ]]; then
+      if [[ $line =~ $section_regex ]]; then
+        if [[ -n ${BASH_REMATCH[1]} ]]; then
+          local -n current_config_array="CONFIG_$(echo ${BASH_REMATCH[1]} | tr '[:lower:]' '[:upper:]')"
+        else
+          echo "section_regex match failed"
+          exit 1
+        fi
+      elif [[ $line =~ $entry_regex ]]; then
+        if [[ -z ${!current_config_array} ]]; then
+          echo "no section defined yet!"
+          exit 1
+        fi
+
+        if [[ -n ${BASH_REMATCH[1]} && -n ${BASH_REMATCH[2]} ]]; then
+          key=$(echo ${BASH_REMATCH[1]} | sed -e 's/^[[:blank:]]+|[[:blank:]]+$//')
+          value=$(echo ${BASH_REMATCH[2]} | sed -e 's/^[[:blank:]]+|[[:blank:]]+$//')
+          current_config_array["${key}"]="${value}"
+        else
+          echo "entry_regex match failed"
+          exit 1
+        fi
+      fi
+    fi
+  done < "$full_path"
+
+  for source_path in ${!CONFIG_SYMLINKS[@]}; do
+    install__link-file-with-announcement \
+      "$(absolute-path-of "$dir/$source_path")" \
+      "${CONFIG_SYMLINKS[$source_path]}"
+  done
+}
+
 install__run-install-script() {
-  local full_source_path="$1"
+  local full_path="$1"
 
   if [[ $VERBOSE -eq 1 ]]; then
-    eval inspect-command env ${GIT_NAME:+'GIT_NAME="$GIT_NAME"'} ${GIT_EMAIL:+'GIT_EMAIL="$GIT_EMAIL"'} '"$full_source_path"'
+    eval inspect-command env ${GIT_NAME:+'GIT_NAME="$GIT_NAME"'} ${GIT_EMAIL:+'GIT_EMAIL="$GIT_EMAIL"'} '"$full_path"'
   fi
 
   if [[ $DRY_RUN -eq 0 ]]; then
     set +e
 
-    eval env ${GIT_NAME:+'GIT_NAME="$GIT_NAME"'} ${GIT_EMAIL:+'GIT_EMAIL="$GIT_EMAIL"'} '"$full_source_path"'
+    eval env ${GIT_NAME:+'GIT_NAME="$GIT_NAME"'} ${GIT_EMAIL:+'GIT_EMAIL="$GIT_EMAIL"'} '"$full_path"'
     exit_code=$?
 
     if [[ $exit_code -ne 0 ]]; then
       echo
-      error "$(format-source-path "$full_source_path") failed with exit code $exit_code."
+      error "$(format-source-path "$full_path") failed with exit code $exit_code."
       echo "Take a closer look at this file. Perhaps you're using set -e and some command is failing?"
       exit 1
     fi
@@ -399,7 +443,7 @@ install__copy-file() {
 
 install__process-non-link() {
   local full_source_path="$1"
-  local non_template_full_source_path="${full_source_path%._no-link}"
+  local non_template_full_source_path="${full_source_path%.__no-link__}"
   local destination_path="${non_template_full_source_path#$PROJECT_DIR/src/}"
   local full_destination_path=$(build-destination-path "$destination_path")
 
@@ -419,7 +463,6 @@ install__process-non-link() {
 install__link-file() {
   local full_source_path="$1"
   local full_destination_path="$2"
-
 
   if [[ $VERBOSE -eq 1 ]]; then
     inspect-command mkdir -p $(dirname "$full_destination_path")
@@ -446,11 +489,24 @@ install__process-entry() {
   local full_source_path="$1"
   local destination_path="${full_source_path#$PROJECT_DIR/src/}"
   local full_destination_path=$(build-destination-path "$destination_path")
+  local basename=$(basename "$full_source_path")
 
-  if [[ $(basename "$full_source_path") == "_install.sh" ]]; then
+  if [[ $basename == "__overrides__.cfg" ]]; then
+    announce config read -s "$full_source_path"
+    install__read-config-file "$full_source_path"
+  elif [[ $basename == "__install__.sh" ]]; then
     announce command run -s "$full_source_path"
     install__run-install-script "$full_source_path"
-  elif [[ -e $full_destination_path ]]; then
+  else
+    install__link-file-with-announcement "$full_source_path" "$full_destination_path"
+  fi
+}
+
+install__link-file-with-announcement() {
+  local full_source_path="$1"
+  local full_destination_path="$2"
+
+  if [[ -e $full_destination_path ]]; then
     if [[ $FORCE -eq 1 ]]; then
       announce link overwrite -s "$full_source_path" -d "$full_destination_path"
       install__link-file "$full_source_path" "$full_destination_path"
@@ -497,9 +553,9 @@ of a few things depending on what it encounters:
 
 There are some exceptions to this:
 
-* If it encounters a file anywhere that ends in ._no-link, it will remove the
+* If it encounters a file anywhere that ends in .__no-link__, it will remove the
   corresponding file from your home directory if it has the same content.
-  EXAMPLE: src/gitconfig._no-link removes a file at ~/.gitconfig if both files
+  EXAMPLE: src/gitconfig.__no-link__ removes a file at ~/.gitconfig if both files
   are the same.
 * If it encounters a directory anywhere that has a .no-recurse file, it will
   NOT recurse the directory; it will remove the symlink for the directory if it
@@ -524,7 +580,7 @@ where OPTIONS are:
   Don't actually change the filesystem.
 --force, -f
   Usually symlinks that do not point to files in src/ and files that end in
-  ._no-link that do not match the file they were copied from are not removed.
+  .__no-link__ that do not match the file they were copied from are not removed.
   This bypasses that.
 --verbose, -V
   Show every command that is run when it is run.
@@ -643,7 +699,7 @@ uninstall__remove-file() {
 
 uninstall__process-non-link() {
   local full_source_path="$1"
-  local non_template_full_source_path="${full_source_path%._no-link}"
+  local non_template_full_source_path="${full_source_path%.__no-link__}"
   local destination_path="${non_template_full_source_path#$PROJECT_DIR/src/}"
   local full_destination_path=$(build-destination-path "$destination_path")
 
@@ -742,7 +798,7 @@ process-entry() {
 
   if [[ -d $full_source_path && ! -e "$full_source_path/.no-recurse" ]]; then
     recurse-dir "$full_source_path"
-  elif [[ $full_source_path =~ \._no-link$ ]]; then
+  elif [[ $full_source_path =~ \.__no-link__$ ]]; then
     ${COMMAND}__process-non-link "$full_source_path"
   else
     ${COMMAND}__process-entry "$full_source_path"
@@ -753,16 +809,24 @@ recurse-dir() {
   local dir="$1"
   local source_path=
 
-  find "$dir"/* -maxdepth 0 -type f -not \( -name _install.sh \) -exec basename {} \; | {
+  # Process /__overrides__.yml
+  if [[ $dir == "$SOURCE_DIR" && -f "$dir/__overrides__.cfg" ]]; then
+    process-entry "__overrides__.cfg" "$dir"
+  fi
+
+  # Process files
+  find "$dir"/* -maxdepth 0 -type f -not \( -name __install__.sh -or -name __overrides__.cfg \) -exec basename {} \; | {
     while IFS= read -r source_path; do
       process-entry "$source_path" "$dir"
     done
   }
 
-  if [[ -f "$dir/_install.sh" && -x "$dir/_install.sh" ]]; then
-    process-entry "_install.sh" "$dir"
+  # Process __install__.sh
+  if [[ -f "$dir/__install__.sh" && -x "$dir/__install__.sh" ]]; then
+    process-entry "__install__.sh" "$dir"
   fi
 
+  # Process subdirectories
   find "$dir"/* -maxdepth 0 -type d -exec basename {} \; | {
     while IFS= read -r source_path; do
       process-entry "$source_path" "$dir"
@@ -779,7 +843,7 @@ main() {
         info "Running in dry-run mode."
         echo
       fi
-      recurse-dir "$PROJECT_DIR/src"
+      recurse-dir "$SOURCE_DIR"
       ${COMMAND}__print-result
       ;;
     *)
